### ISSUE TITLE
Arbitrary resolutions

### ISSUE THREAD

**Issue by Keith94** [ForsakenX/forsaken#285]
Hi, can you tell me if ProjectX supports arbitrary resolutions, such as ultra-widescreen (2560x1080, 3440x1440), multi-monitor resolutions (5760x1080 etc.) and 4K resolution (3840x2160), with proper aspect ratio/FOV ? Thanks.

**Comment by chino** [comment]
I'm pretty sure you can force those settings to specific values via command
line flags documented on the wiki. I've definitely ran it on 1080 with 3d
support!  Check there and let me know if that works out?

**Comment by Keith94** [comment]
I tried forcing some custom resolutions in windowed mode but the wiki states that "Values *must* be valid resolutions for your device.", this means I cannot test dual monitor resolutions or things like that unforunately.

**Comment by chino** [comment]
Hm, I'm pretty sure that window mode is just "scaled" so it doesn't have to fit "valid resolutions for your device" (which should only apply for full screen mode).  Have you tried resizing the window mode across two screens?  Also if you're OS supports treating two monitors as one giant monitor then you're OS would handle that as a valid resolution I believe.

Let me know how that goes.

As far as multi-monitor support there have been some ideas in the past (like rear/missile view in a second window) but was never built.  It shouldn't be too hard if you have some programming skills to go after that though.

**Comment by Keith94** [comment]
Resizing the game window manually doesn't seem to be supported on Windows.

I don't know why but the "valid resolution" rule must apply to windowed mode as well (in this case).

I can run a Unity engine game across my dual monitors in windowed mode via command line `-screen-width 3840 -screen-height 1080`. But if I try the same for Forsaken port with `-mode:3840:1080`, it just launches in 640x480 window.

**Comment by chino** [comment]
I haven't played with this stuff in a while but it does look like the cli flags would try to fit to one of the standard modes: 

https://github.com/ForsakenX/forsaken/blob/master/main_sdl.c#L94

The list is defined here:

https://github.com/ForsakenX/forsaken/blob/master/main_sdl.c#L53

You're saying that stretching it across two monitors manually doesn't work?

I think that's here iirc:

https://github.com/ForsakenX/forsaken/blob/master/input_sdl.c#L96
https://github.com/ForsakenX/forsaken/blob/master/render_gl_shared.c#L555

You could also check in the log to see what kind of messages it pops out.

I'd have to hook up the game to a multi monitor setup and try it out to see what I could do.

**Comment by Keith94** [comment]
Basically if I try to launch the game at any non-standard resolution, like 1600x500, 1920x800, 3840x1080, they simply don't work. You could test it with a single monitor. Dragging window borders to resize doesn't work either...

I was also curious if it supports very high resolutions (like 4K res or above) without issue.

**Comment by chino** [comment]
Resizing definitely use to work just fine.  I'll see if I can take a look at it.

I'm not sure such high resolutions really matter for such an old game especially given the quality of the textures?

**Comment by Keith94** [comment]
Ahh good point, mainly was just wondering how the game handled it especially with scaling HUD, menus etc. but it's not a big deal.

Thanks for taking a look.

**Comment by chino** [comment]
I have screenshots of it running on 1080 55" with 3d so not sure what to say without debugging it on your setup.  There is tons of possible combinations that makes this sort of thing tough.  The game right now just uses SDL as I linked to above so patches welcome or if you want to help debug :]  If we ever finish the port to the newer SDL might fix it.

I'll close for now but feel free to comment further.
