### ISSUE TITLE
Microstutter

### ISSUE THREAD

**Issue by Tarhkken** [ForsakenX/forsaken#286]
game microstutters when playing the game every 3 minutes or so? very odd? have to play the game in its original state via patch 1.01

**Comment by chino** [comment]
I haven't heard anyone else say this and there hasn't been changes for a while now so I'd assume something going on with your system.

Can you give any more details on what os/version you're on, what you were doing to trigger it, perhaps debug logs or try to attach a debugger and see where it gets hung up?

**Comment by chino** [comment]
I guess if there is further issues or if you have any kind of debug output that could lead to a fix would be great.

I'll close for now but definitely update the issue if it's still a problem.
